Convert Arrow Function to ES5
kevva/strict-uri-encode pull request #12
Opened 2019-03-20 21:41 UTC by trevorlitsey

I know this issue has been covered. Hoping that you will reconsider writing this fine lib as a good 'ol function.

I understand not wanting to target for the browser, but for this library at least, it's one very small fix for that would save a lot of folks an extra dependency. JS devs everywhere will thank you!

Thanks for considering.

2019-04-03 12:29 UTC, buz-zard commented on index.js
> +	return encodeURIComponent(str).replace(/[!'()*]/g, x => `%${x.charCodeAt(0).toString(16).toUpperCase()}`);
`x => `%${x.charCodeAt(0).toString(16).toUpperCase()` I think this also should be converted to `function(...`

2019-06-27 17:59 UTC, karolis-sh requested changes

2019-06-27 17:59 UTC, buz-zard commented on index.js
> +			.toUpperCase()}`;
```
		return '%' + x
			.charCodeAt(0)
			.toString(16)
			.toUpperCase();
```

same thing as with arrow functions

https://caniuse.com/#search=arrow%20functions
https://caniuse.com/#search=template

2019-09-09 16:57 UTC, kevva commented
Arrow functions and template literals are both supported in newer version of all major browsers.

2019-09-09 16:57 UTC, closed without merging